/* ********************************************************************* */
/* *********************** CONFIGURAZIONE ****************************** */
/* ********************************************************************* */

/* *************** SCHEDE PRODOTTO (PAG + SCHEDA ) *********************** */
var schedaSmartHome = "https://www.terrecablate.it/pdf/MD.CO.04.SchedaProdottoSmartHome.22.pdf";
var pagSmartHome = "https://www.terrecablate.it/casa/smart-home/";

var schedaSmartOffice = "https://www.terrecablate.it/pdf/MD.CO.08.SchedaProdotto-SmartOffice.22.pdf";
var pagSmartOffice = "https://www.terrecablate.it/azienda/smart-office/";

var schedaSmartOffice2 = "https://www.terrecablate.it/pdf/MD.CO.08.2SchedaProdottoSmartOffice2.22.pdf";
var pagSmartOffice2 = "https://www.terrecablate.it/azienda/smart-office-2/";

var schedaSmartOffice4 = "https://www.terrecablate.it/pdf/MD.CO.08.3SchedaProdottoSmartOffice4.22.pdf";
var pagSmartOffice4 = "https://www.terrecablate.it/azienda/smart-office-4/";

var schedaSmartOfficeFtth = "https://www.terrecablate.it/pdf/MD.CO.08.4SchedaProdottoSmartOfficeFTTH.22.pdf";
var schedaSmartOffice2Ftth = "https://www.terrecablate.it/pdf/MD.CO.08.5SchedaProdottoSmartOffice2FTTH.22.pdf";
var schedaSmartOffice4Ftth = "https://www.terrecablate.it/pdf/MD.CO.08.6SchedaProdottoSmartOffice4FTTH.22.pdf";

/* ************* FEATURES ************************************ */
var featHome = "1 linea telefonica (chiamate a consumo);Fibra Ultraveloce;Modem UltraFibra WiFi;Casella Posta Elettronica Certificata";
var featOffice =
  "1 linea telefonica (chiamate comprese fino a 2000 minuti verso i fissi e 200 minuti verso i mobili);Internet illimitato fino a 1 Gbps;Modem UltraFibra WiFi;1 indirizzo IP statico;Identificativo del chiamante GRATUITO";
var featOffice2 =
  "2 linee telefoniche(chiamate comprese fino a 2500 minuti verso i fissi e 250 minuti verso i mobili);Internet illimitato fino a 1Gbps;Modem UltraFibra WiFi;1 indirizzo IP statico;Identificativo del chiamante GRATUITO";
var featOffice4 =
  "4 linee telefoniche (chiamate comprese fino a 3000 minuti verso i fissi e 300 minuti verso i mobili);Internet illimitato fino a 1 Gbps;Modem UltraFibra WiFi;1 indirizzo IP statico;Identificativo del chiamante GRATUITO";

var featOfficePlus =
  "1 linea telefonica (chiamate comprese fino a 2000 minuti verso i fissi e 200 minuti verso i mobili);Internet illimitato fino a 2,5 Gbps;1 indirizzo IP statico;Identificativo del chiamante GRATUITO;Router premium Fritxbox con: WiFi 6 per le massime prestazioni;1 porta telefono fisso;base DECT integrata (fino 6 cordless) + 1 Extender 1200AX per raggiungere ogni angolo della tua azienda + 1 Telefono DECT FRITZ!Fon C6 + 1 Fax2mail + Installazione e configurazione + Business Assistance";

var featOffice2Plus =
  "2 linee telefoniche(chiamate comprese fino a 2500 minuti verso i fissi e 250 minuti verso i mobili);Internet illimitato fino a 2,5 Gbps;1 indirizzo IP statico;Identificativo del chiamante GRATUITO;Router premium Fritxbox con: WiFi 6 per le massime prestazioni;1 porta telefono fisso;base DECT integrata (fino 6 cordless) + Centralino Telefonico+1 Extender 1200AX per raggiungere ogni angolo della tua azienda + 2 Telefoni DECT FRITZ!Fon C6 + 1 Fax2mail + Installazione e configurazione  + Business Assistance";

var featOffice4Plus =
  "4 linee telefoniche (chiamate comprese fino a 3000 minuti verso i fissi e 300 minuti verso i mobili);Internet illimitato fino a 2,5 Gbps;1 indirizzo IP statico;Identificativo del chiamante GRATUITO;Router premium Fritxbox con: WiFi 6 per le massime prestazioni;1 porta telefono fisso;base DECT integrata (fino 6 cordless) + Centralino Telefonico + 1 Extender 1200AX per raggiungere ogni angolo della tua azienda + 4 Telefoni DECT FRITZ!Fon C6 + 1 Fax2mail + Installazione e configurazione + Business Assistance";

/* ************* CONTRATTI *********************************** */
var CONTRATTO_HOME = "https://www.terrecablate.it/pdf/MD.CO.03.Contratto_Residenziali22.pdf";
var CONTRATTO_OFFICE = "https://www.terrecablate.it/pdf/MD.CO.07.Contratto_Aziende22.pdf";
var CONTRATTO_OFFICE_FTTH = "https://www.terrecablate.it/pdf/MD.CO.07.Contratto_SmartOffice_FTTH22.pdf";

/* ********************************************************************************************************************************************************************* */

var prodotti = {
  aziende: {
    "TCRS_GPON-1000/300E": {
      down: "1000",
      up: "300",
      bmg: "30",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Office FTTH",
          canone: "37,78",
          voucher: {
            prezzo: "10,00",
            iva: "8,31",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "30",
          },
          image: "smartofficeftth_300.png",
          link: "https://www.terrecablate.it/azienda/smart-office-ftth/",
          scheda: schedaSmartOfficeFtth,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2 FTTH",
          canone: "52,78",
          voucher: {
            prezzo: "25,00",
            iva: "11,61",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice2Ftth,
            bmg: "30",
          },
          image: "smartoffice2ftth_300.png",
          link: "https://www.terrecablate.it/azienda/smart-office-2ftth/",
          scheda: schedaSmartOffice2Ftth,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4 FTTH",
          canone: "72,78",
          voucher: {
            prezzo: "45,00",
            iva: "16,01",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice4Ftth,
            bmg: "30",
          },
          image: "smartoffice4ftth_300.png",
          link: "https://www.terrecablate.it/azienda/smart-office-4ftth/",
          scheda: schedaSmartOffice4Ftth,
          features: featOffice4,
        },
        {
          prodotto: "Smart Office PLUS",
          canone: "92,33",
          voucher: {
            prezzo: "45,00",
            iva: "16,01",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice4Ftth,
            bmg: "30",
          },
          image: "smartoffice4ftth_300.png",
          link: "https://www.terrecablate.it/azienda/smart-office-4ftth/",
          scheda: schedaSmartOffice4Ftth,
          features: featOffice4,
        },
      ],
    },

    "TCRS_GPON-1000/300": {
      down: "1000",
      up: "300",
      bmg: "10",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "8,31",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "30",
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "11,61",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: "30",
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "16,01",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: "30",
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },

    "OF_FTTH-1000/300": {
      down: "1000",
      up: "300",
      bollino: "bollinoF.png",
      bmg: "10",
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "8,31",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "30",
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "11,61",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: "30",
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "16,01",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER B",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: "30",
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },

    "VULA FTTH-1000/300": {
      down: "1000",
      up: "300",
      bmg: "10",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,87",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "10",
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: "10",
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,87",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: "10",
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Bitstream NGA FTTH-1000/300": {
      down: "1000",
      up: "300",
      bmg: "10",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,87",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "10",
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: "10",
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,87",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: "10",
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },

    // FIBRECONNECT
    "GPON_FC-1000/300": {
      down: "1000",
      up: "300",
      bmg: "1",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: "1",
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "56,67",
          voucher: {
            prezzo: "40,00",
            iva: "12,47",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: "1",
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "76,67",
          voucher: {
            prezzo: "60,00",
            iva: "16,87",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A2",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: "11",
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },

    "VDSL_AI-100/20": {
      down: "100",
      up: "20",
      bollino: "bollinoFR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "VULA-200/20": {
      down: "200",
      up: "20",
      bollino: "bollinoFR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "VULA-100/20": {
      down: "100",
      up: "20",
      bollino: "bollinoFR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Bitstream NGA-200/20": {
      down: "200",
      up: "20",
      bollino: "bollinoFR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Bitstream NGA-100/20": {
      down: "100",
      up: "20",
      bollino: "bollinoFR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Rame su AI-20/1": {
      down: "20",
      up: "1",
      bollino: "bollinoR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "ULL-20/1": {
      down: "20",
      up: "1",
      bollino: "bollinoR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Bitstream Ethernet-20/1": {
      down: "20",
      up: "1",
      bollino: "bollinoR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
    "Bitstream-7/0,7": {
      down: "7",
      up: "0,7",
      bollino: "bollinoR.png",
      bmg: null,
      offerte: [
        {
          prodotto: "Smart Office",
          canone: "26,67",
          voucher: {
            prezzo: "10,00",
            iva: "5,878",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice,
            bmg: null,
          },
          image: "smartoffice.png",
          link: pagSmartOffice,
          scheda: schedaSmartOffice,
          features: featOffice,
        },
        {
          prodotto: "Smart Office 2",
          canone: "41,67",
          voucher: {
            prezzo: "25,00",
            iva: "9,17",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice2,
            bmg: null,
          },
          image: "smartoffice2.png",
          link: pagSmartOffice2,
          scheda: schedaSmartOffice2,
          features: featOffice2,
        },
        {
          prodotto: "Smart Office 4",
          canone: "61,67",
          voucher: {
            prezzo: "45,00",
            iva: "13,57",
            durata: "18 mesi",
            tipoVoucher: "VOUCHER A1",
            allaccio: null,
            scheda: schedaSmartOffice4,
            bmg: null,
          },
          image: "smartoffice4.png",
          link: pagSmartOffice4,
          scheda: schedaSmartOffice4,
          features: featOffice4,
        },
      ],
    },
  },
  residenziali: {
    "TCRS_GPON-1000/300": {
      down: "1000",
      up: "300",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "OF_FTTH-1000/300": {
      down: "1000",
      up: "300",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "VULA FTTH-1000/300": {
      down: "1000",
      up: "300",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "Bitstream NGA FTTH-1000/300": {
      down: "1000",
      up: "300",
      bollino: "bollinoF.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    // "TCRS_GPON-100/20": {
    //   down: "100",
    //   up: "20",
    //   bollino: "bollinoF.png",
    //   offerte: [
    //     {
    //       prodotto: "Smart Home",
    //       canone: "28,95",
    //       voucher: null,
    //       image: "smarthome.png",
    //       link: pagSmartHome,
    //       scheda: schedaSmartHome,
    //       features: "1 linea telefonica; Modem wifi ultrafibra incluso; 1500 min/mese verso fissi nazionali; 60 min/mese verso mobili nazionali",
    //     },
    //   ],
    // },
    "VULA-200/20": {
      down: "200",
      up: "20",
      bollino: "bollinoFR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "VULA-100/20": {
      down: "100",
      up: "20",
      bollino: "bollinoFR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "Bitstream NGA-200/20": {
      down: "200",
      up: "20",
      bollino: "bollinoFR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "Bitstream NGA-100/20": {
      down: "100",
      up: "20",
      bollino: "bollinoFR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "ULL-20/1": {
      down: "20",
      up: "1",
      bollino: "bollinoR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "Bitstream Ethernet-20/1": {
      down: "20",
      up: "1",
      bollino: "bollinoR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
    "Bitstream-7/0,7": {
      down: "7",
      up: "0,7",
      bollino: "bollinoR.png",
      offerte: [
        {
          prodotto: "Smart Home",
          canone: "23,90",
          voucher: null,
          image: "smarthome.png",
          link: pagSmartHome,
          scheda: schedaSmartHome,
          features: featHome,
        },
      ],
    },
  },
};

// var prodottiVoceFax = {
//   smarthomevoce: {
//     prodotto: "Smart Home Voce",
//     canone: "19,95",
//     image: "smarthomevoce.png",
//     link: "https://www.terrecablate.it/casa/smart-home-voce/",
//   },
//   smartofficevoce: {
//     prodotto: "Smart Office Voce",
//     canone: "23,00",
//     image: "smartofficevoce.png",
//     link: "https://www.terrecablate.it/azienda/smart-office-voce/",
//   },
//   smartofficefax: {
//     prodotto: "Smart Office Fax",
//     canone: "4,00",
//     image: "smartofficefax.png",
//     link: "https://www.terrecablate.it/azienda/smart-office-fax/",
//   },
//   smartofficeisdn: {
//     prodotto: "Smart Office ISDN",
//     canone: "35,00",
//     image: "smartofficeisdn.png",
//     link: "https://www.terrecablate.it/azienda/smart-office-isdn/",
//   },
// };
